<div class="block-group box-section">
	<div class="countdown-wrapper">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('saleslider.phtml')->toHtml();?> 
		</div>
	</div>
	<div class="bestsell-wr">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('bestsellerproduct.phtml')->toHtml();?>
		</div>
	</div>
	<div class="testimo-wr">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('testimonial.phtml')->toHtml();?> 
	</div>
	<div class="blog-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
	</div>
	<div class="container">
		<div class="line_bot">
			<div class="row">
				<div class="col-md-4 col-sm-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('newproductslider.phtml')->toHtml();?> 
				</div>			
				<div class="col-md-4 col-sm-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Saleproductslider\Block\Saleproductslider')->setTemplate('saleproductslider.phtml')->toHtml();?> 
				</div>	
				<div class="col-md-4 col-sm-12 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('featureproductslider.phtml')->toHtml();?> 				
				</div>
			</div>
		</div>
	</div>	
	<div class="cat_top">		
		<?php echo $block->getLayout()->createBlock('Plazathemes\Categorytop\Block\Categorytop')->setTemplate('categorytop.phtml')->toHtml();?>
	</div>	

</div>