<?php $block->renderFileLessToCss(); ?>

<header id="lucian_header123" class="header-container">
	<div class="top-link">
		<div class="container">
			<div class="box-left">
				<?php echo $this->getChildHtml("header_hello"); ?>
<a href="<?php /* @escapeNotVerified */ echo $block->getUrl().'customer/account/create'; ?>" title="<?php echo __('Register'); ?>"><?php echo __('Register'); ?></a>
<span>or</span>
<a href="<?php /* @escapeNotVerified */ echo $block->getUrl().'customer/account/login'; ?>" title="<?php echo __('Login'); ?>"><?php echo __('Login'); ?></a>				

			</div>
			<div class="box-right visible-lg visible-md">
				<div class="top-link-dropdown">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="language-currency">
					<?php echo $this->getChildHtml("currency"); ?>				
					<?php echo $this->getChildHtml("store_language"); ?>
				</div>					
			</div>
		</div>
	</div>
	<div class="header-content header-wr">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-12 visible-lg visible-md">
					<div class="logo-home">
						<?php echo $this->getChildHtml("logo"); ?>
					</div>
				</div>
				<div class="col-md-7 col-sm-0 col-sms-12">
					<div class="hidexs">
						<span class="navbar-brand">Menu Link</span>
						<button class="toggle-nav">
							<span class="icon-menu">
								<span class="line line-1"></span>
								<span class="line line-2"></span>
								<span class="line line-3"></span>
							</span>
						</button>	
					</div>
					<?php echo $block->getLayout()->createBlock('Plazathemes\Hozmegamenu\Block\Menu')->setTemplate('hozmegamenu.phtml')->toHtml();?> 
				</div>				
				<div class="col-md-2 col-sms-12 visible-lg visible-md">
					<div class="top-cart-wrapper">
						<?php echo $this->getChildHtml("minicart");?>
					</div>	
				</div>
			</div>
		</div>
	</div>
	<div class="header-bottom visible-lg visible-md">
		<div class="container">
			<div class="row">	
				<div class="col-md-3 col-sm-0 col-sms-12  visible-lg visible-md">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Hozmegamenu\Block\Menu')->setTemplate('verticalmegamenu.phtml')->toHtml();?> 					
				</div>
				<div class="col-md-7 col-sms-12 visible-lg visible-md">
					<?php echo $this->getChildHtml("top.search"); ?>
				</div>
				<div class="col-md-2 col-sms-12 visible-lg visible-md">
					<?php echo $this->getChildHtml("header_phone"); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="header-mobile visible-xs">
		<div class="container">
			<div class="header-mobile-container"> 
				<?php echo $this->getChildHtml("top.search.mobile"); ?>
				<?php echo $this->getChildHtml("logo"); ?> 
				<div class="my-account close-box">  
					<span class="close-icon"> <?php echo __('close icon')?></span> 
					<div id="tabs-menu">
						<ul class="tabs">
							<li class="tab active"><a href="#tab-content-1"><?php echo __('categories')?></a></li>
							<li class="tab"><a href="#tab-content-2"><?php echo __('setting')?></a></li>
						</ul>
						<div class="tabs-content">
							<div id="tab-content-1" class="tab-content active"><?php echo $this->getChildHtml("mobilemenu");?></div>
							<div id="tab-content-2" class="tab-content">
								
								<?php echo $this->getChildHtml("header_info"); ?>
								<?php echo $this->getChildHtml("header_social"); ?> 
								<?php echo $this->getChildHtml("header.links"); ?> 
								<?php echo $this->getChildHtml("currency.mobile"); ?>
								<?php echo $this->getChildHtml("languages.mobile"); ?>
								 
							</div>
						</div>
						
					</div> 
				</div>
				<div class="box-right">
					<span class="open-icon mb-icon"> <?php echo __('open icon')?></span>  
				</div>
			</div>
		</div>
	</div>
</header>

<script type="text/javascript"> 
require(["jquery"], function(jQuery){
		var html = jQuery('html, body'),
			pt_Custommenu = jQuery('.pt_custommenu'),
			toggleNav = jQuery('.toggle-nav'),
			navDropdownToggle = jQuery('.has-dropdown');

		// Nav toggle
		toggleNav.on('click', function(e) {
			e.preventDefault();
			jQuery(this).toggleClass('is-active');
			pt_Custommenu.toggleClass('is-visible');
			html.toggleClass('nav-open');
		});

		// Nav dropdown toggle
		navDropdownToggle.on('click', function() {
			jQuery(this).toggleClass('is-active').children('ul').toggleClass('is-visible');
		});

		// Prevent click events from firing on children of navDropdownToggle
		navDropdownToggle.on('click', '*', function(e) {
			e.stopPropagation();
		});	
	jQuery(".header-mobile .open-icon").click(function() {
		var chk=0;
		if(jQuery('.header-mobile .my-account').hasClass('close-box') && (chk==0)) {
			jQuery('.header-mobile .my-account').removeClass('close-box');
			jQuery('.header-mobile .my-account').addClass('open-box'); 
			jQuery('.header-mobile .open-icon').addClass('close-icon');    
			chk=1;
		}   
		if(jQuery('.header-mobile .my-account').hasClass('open-box') && (chk==0)) {
			jQuery('.header-mobile .my-account').removeClass('open-box');
			jQuery('.header-mobile .my-account').addClass('close-box'); 
			jQuery('.header-mobile .open-icon').removeClass('close-icon');   
			chk=1;
		} 
	});  
	jQuery(".header-mobile .close-icon").click(function() {
		if(jQuery('.header-mobile .my-account').hasClass('open-box')) {
			jQuery('.header-mobile .my-account').removeClass('open-box');
			jQuery('.header-mobile .my-account').addClass('close-box');
			jQuery('.header-mobile .open-icon').removeClass('close-icon'); 

		}   
	});
	jQuery('#tabs-menu .tabs li a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('#tabs-menu ' + currentAttrValue).show().siblings().hide();
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
    if ( jQuery(window).width() < 600 ) {
     	jQuery('.header-mobile .block-search .block-title').click(function(){
    		jQuery('.header-mobile .block-search .block-content').append('<span class="close-icon">close-icon</span>').slideDown(300);  
			jQuery('.header-mobile .block-search .block-content .close-icon').click(function(){
				jQuery(this).parent('.header-mobile .block-search .block-content').slideUp(300); 
				jQuery(this).remove();				
			} );
     	} ); 
    }
	
	if(jQuery(window).width() < 992) {
		jQuery('.minicart-moveable').insertAfter(jQuery('.mb-icon'));
	}	
	jQuery(window).scroll(function(){
		if(jQuery(this).scrollTop() > 140){
			jQuery(".header-wr").addClass("fix-nav");
		}else{
			jQuery(".header-wr").removeClass("fix-nav");
		}
	});		
}); 
</script>

