<div class="block-group box-section">

	<div class="container">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_static_h3')->toHtml();?>
		<div class="line_bot">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('featureproductslider.phtml')->toHtml();?> 				
		</div>
	</div>	
	<div class="blog-slider">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
	</div>	
	<div class="cat_top">		
		<?php echo $block->getLayout()->createBlock('Plazathemes\Categorytop\Block\Categorytop')->setTemplate('categorytop.phtml')->toHtml();?>
	</div>	

</div>